#!/usr/bin/env bash
# Detect a newly published Anytype API spec version and bump the pinned
# references in the repo.
#
# Reads the latest entry from
#   https://raw.githubusercontent.com/anyproto/anytype-api/refs/heads/main/docs/reference/versions.json
# compares it against the version currently pinned in
# internal/client/client.go (the `APIVersion` constant), and — if a newer
# version is available — rewrites:
#
#   - internal/client/client.go  (APIVersion constant)
#   - GNUmakefile                (OPENAPI_URL default)
#
# The generated code itself (codegen/openapi.yaml,
# codegen/provider_code_spec.json, internal/generated/**) is gitignored and
# regenerated by CI; this script does not touch it.
#
# Machine-readable values are written to $GITHUB_OUTPUT when the variable is
# set (i.e. when running inside GitHub Actions):
#   - current_version       the version that was pinned
#   - latest_version        the latest published version
#   - latest_download_url   the download URL of the latest spec
#   - changed               "true" if the pinned version was updated
set -euo pipefail

VERSIONS_JSON_URL="${VERSIONS_JSON_URL:-https://raw.githubusercontent.com/anyproto/anytype-api/refs/heads/main/docs/reference/versions.json}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLIENT_FILE="$REPO_ROOT/internal/client/client.go"
MAKEFILE="$REPO_ROOT/GNUmakefile"

require() {
	command -v "$1" >/dev/null 2>&1 || {
		echo "error: required command '$1' is not on PATH" >&2
		exit 2
	}
}

require curl
require jq

emit_output() {
	local key="$1" value="$2"
	echo "$key=$value"
	if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
		echo "$key=$value" >>"$GITHUB_OUTPUT"
	fi
}

current_version=$(grep -E '^\s*APIVersion\s*=' "$CLIENT_FILE" | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
if [[ -z "$current_version" ]]; then
	echo "error: could not extract APIVersion from $CLIENT_FILE" >&2
	exit 1
fi

versions_json=$(curl -fsSL "$VERSIONS_JSON_URL")
latest_version=$(echo "$versions_json" | jq -r '.[0].version')
latest_download=$(echo "$versions_json" | jq -r '.[0].downloadUrl')

if [[ -z "$latest_version" || "$latest_version" == "null" ]]; then
	echo "error: could not parse latest version from $VERSIONS_JSON_URL" >&2
	exit 1
fi

emit_output current_version "$current_version"
emit_output latest_version "$latest_version"
emit_output latest_download_url "$latest_download"

if [[ "$current_version" == "$latest_version" ]]; then
	emit_output changed "false"
	echo "Already on the latest Anytype API version ($current_version)."
	exit 0
fi

emit_output changed "true"
echo "New Anytype API version available: $current_version -> $latest_version"

sed -i.bak -E "s|(APIVersion\s*=\s*\")[^\"]+(\")|\1$latest_version\2|" "$CLIENT_FILE"
rm -f "$CLIENT_FILE.bak"

sed -i.bak -E "s|(OPENAPI_URL\s*\\?=\\s*).*|\1$latest_download|" "$MAKEFILE"
rm -f "$MAKEFILE.bak"

echo "Pinned Anytype API version bumped to $latest_version."
